name: "config-service"
on:
  push:
    tags:
      - '*'
    branches:
      - main
    paths:
      - "services/config/**"
  pull_request:
    paths:
      - "services/config/**"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: "Check out"
      uses: actions/checkout@v2
    - name: "Set up Java and maven cache"
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt-hotspot'
        java-version: '11'
        check-latest: true
        cache: 'maven'

    - name: "Install & check formatting"
      run: ./mvnw verify -f services/config/ -ntp -Dfmt.action=check
